### ISSUE TITLE
Error installing the zip file

### ISSUE THREAD

**Issue by smrutiranjan7274** [PotatoDevices/device_redmi_begonia#6]
While trying to install on my redmi note 8 pro, its showing the above error

**Comment by HyperNotAryanX97** [comment]
> While trying to install on my redmi note 8 pro, its showing the above error

Where is error ?

**Comment by smrutiranjan7274** [comment]
twrp

**Comment by HyperNotAryanX97** [comment]
> twrp

What twrp ?
Show error.

**Comment by smrutiranjan7274** [comment]
![IMG_20210527_161454](https://user-images.githubusercontent.com/67579934/119813462-ef464180-bf06-11eb-9c70-ab73f702bd0f.jpg)

**Comment by HyperNotAryanX97** [comment]
@smrutiranjan7274 Try Latest Unified TWRP

**Comment by smrutiranjan7274** [comment]
could you assist me regarding this through telegram?

**Comment by HyperNotAryanX97** [comment]
> could you assist me regarding this through telegram?

Yes why not @UNKNOWN_MEMBER_69 is my id
